### ISSUE TITLE
对非At类型的消息添加触发At的触发器

### ISSUE THREAD

**Issue by RobertIndie** [Genanik/AbelBotPlugin#1]
如有时候会出现下列情形：
![image](https://user-images.githubusercontent.com/16974619/89126410-0a7b3700-d518-11ea-92bb-b5c02b344686.png)

估计是[这里](https://github.com/Genanik/AbelBotPlugin/blob/master/src/main/kotlin/io/genanik/miraiPlugin/AbelPluginMain.kt#L143)使用了`firstIsInstanceOrNull`导致只获取了最近的消息。

**Comment by Genanik** [comment]
哈吉那条消息没有At到大火啊喂😂
不过这个确实影响了使用体验，我有时间考虑下咋优化优化（

**Comment by Genanik** [comment]
mirai并没有开放相关api修改消息队列🙃，不能实现
